language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86  
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
  - julia: nightly  
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
codecov: true
